package com.info.model;

import java.io.Serializable;
import java.util.Date;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.OnDelete;
import org.hibernate.annotations.OnDeleteAction;
/**
 * Entity class for company.
 */
@Entity
@Table(name = "company")
public class Company implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	/**
	 * id of company. Automatically generated by database.
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;
	
	/**
	 * Set of {@link com.info.model.Employee}s of this company.
	 */
	@OneToMany(mappedBy="company", cascade = CascadeType.REMOVE)
	@OnDelete(action=OnDeleteAction.CASCADE)
	private Set<Employee> employees;
	
	/**
	 * Set of {@link com.info.model.File}s of this company.
	 */
	@OneToMany(mappedBy="company", cascade = CascadeType.REMOVE)
	@OnDelete(action=OnDeleteAction.CASCADE)
	private Set<File> files;
	
	/**
	 * Id of {@link com.info.model.Ownership} which this company has.
	 * Mandatory field.
	 */
	private int ownership;
	
	/**
	 * Id of {@link com.info.model.Legalform} which this company has.
	 * Mandatory field.
	 */
	private int legalform;
	
	/**
	 * Name of company.
	 * Mandatory field. 
	 * Can contain only letters, digits, hyphens, and spaces and cannot be greater than 50 characters.
	 */
	private String name;
	
	/**
	 * Company manager name.
	 * Mandatory field.
	 * Can contain only letters, hyphens, and spaces and cannot be greater than 50 characters.
	 */
	private String managername;

	/**
	 * Fax of company.
	 * Optional field.
	 * If available, must be 12 digits in length.
	 */
	private String fax;

	/**
	 * Phone of company.
	 * Mandatory field.
	 * Must be 12 digits in length.
	 */
	private String phone;
	
	/**
	 * Company's web page.
	 * Optional field.
	 * If available, must match {@code (https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w \.-]*)*\/?} pattern.
	 */
	private String webpage;
	
	/**
	 * Company's license.
	 * Mandatory field.
	 * Must be unique and cannot be greater than 30 characters. Can contain any character.
	 */
	@Column(unique=true)
	private String license;
	
	/**
	 * Date when license was given.
	 * Mandatory field.
	 */
	private Date licensedate;
	
	/**
	 * Company's certificate.
	 * Mandatory field.
	 * Cannot be greater than 30 characters. Can contain any character.
	 */
	private String certificate;
	
	/**
	 * Date when certificate was given.
	 * Mandatory field.
	 */
	private Date certdate;
	
	/**
	 * Company's address.
	 * Mandatory field.
	 * Cannot be greater than 50 characters. Can contain any characters.
	 */
	private String address;

	/**
	 * Default constructor.
	 */
	public Company() {
		super();
	}

	/**
	 * Getter method for {@link #id}.
	 * @return id of company.
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * Setter method for {@link #id}.
	 * @param id id of company to set.
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * Getter method for {@link #employees}.
	 * @return employees of company.
	 */
	public Set<Employee> getEmployees() {
		return employees;
	}

	/**
	 * Setter method for {@link #employees}.
	 * @param employees Set of employees to set.
	 */
	public void setEmployees(Set<Employee> employees) {
		this.employees = employees;
	}

	/**
	 * Getter method for {@link #ownership}.
	 * @return ownership of company.
	 */
	public int getOwnership() {
		return ownership;
	}

	/**
	 * Setter method for {@link #ownership}.
	 * @param ownership ownership of company to set.
	 */
	public void setOwnership(int ownership) {
		this.ownership = ownership;
	}

	/**
	 * Getter method for {@link #legalform}.
	 * @return legal form of company.
	 */
	public int getLegalform() {
		return legalform;
	}

	/**
	 * Setter method for {@link #legalform}.
	 * @param legalform legal form of company to set.
	 */
	public void setLegalform(int legalform) {
		this.legalform = legalform;
	}

	/**
	 * Getter method for {@link #name}.
	 * @return name of company.
	 */
	public String getName() {
		return name;
	}

	/**
	 * Setter method for {@link #name}.
	 * @param name name of company to set.
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Getter method for {@link #managername}.
	 * @return name of manager.
	 */
	public String getManagername() {
		return managername;
	}

	/**
	 * Setter method for {@link #managername}.
	 * @param managername name of manager to set.
	 */
	public void setManagername(String managername) {
		this.managername = managername;
	}

	/**
	 * Getter method for {@link #fax}.
	 * @return fax of company.
	 */
	public String getFax() {
		return fax;
	}

	/**
	 * Setter method for {@link #fax}.
	 * @param fax fax of company to set.
	 */
	public void setFax(String fax) {
		this.fax = fax;
	}

	/**
	 * Getter method for {@link #phone}.
	 * @return phone of company.
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * Setter method for {@link #phone}.
	 * @param phone phone of company to set.
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * Getter method for {@link #webpage}.
	 * @return webpage of company.
	 */
	public String getWebpage() {
		return webpage;
	}

	/**
	 * Setter method for {@link #webpage}.
	 * @param webpage webpage of company to set.
	 */
	public void setWebpage(String webpage) {
		this.webpage = webpage;
	}

	/**
	 * Getter method for {@link #license}.
	 * @return license of company.
	 */
	public String getLicense() {
		return license;
	}

	/**
	 * Setter method for {@link #license}.
	 * @param license license of company to set. 
	 */
	public void setLicense(String license) {
		this.license = license;
	}

	/**
	 * Getter method for {@link #licensedate}.
	 * @return date when license was given.
	 */
	public Date getLicensedate() {
		return licensedate;
	}

	/**
	 * Setter method for {@link #licensedate}.
	 * @param licensedate date when license was given to set.
	 */
	public void setLicensedate(Date licensedate) {
		this.licensedate = licensedate;
	}

	/**
	 * Getter method for {@link #certificate}.
	 * @return certificate of company.
	 */
	public String getCertificate() {
		return certificate;
	}

	/**
	 * Setter method for {@link #certificate}.
	 * @param certificate certificate of company to set. 
	 */
	public void setCertificate(String certificate) {
		this.certificate = certificate;
	}

	/**
	 * Getter method for {@link #certdate}.
	 * @return date when certificate was given.
	 */
	public Date getCertdate() {
		return certdate;
	}

	/**
	 * Setter method for {@link #certdate}.
	 * @param certdate date when certificate was given to set.
	 */
	public void setCertdate(Date certdate) {
		this.certdate = certdate;
	}

	/**
	 * Getter method for {@link #address}.
	 * @return address of company.
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * Setter method for {@link #address}.
	 * @param address address of company.
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * Getter method for {@link #files}.
	 * @return Set of files of company.
	 */
	public Set<File> getFiles() {
		return files;
	}

	/**
	 * Setter method for {@link #files}.
	 * @param files Set of files of company to set.
	 */
	public void setFiles(Set<File> files) {
		this.files = files;
	}
}
