package com.info.model;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Entity class for uploaded file.
 */
@Entity
@Table(name = "file")
public class File implements Serializable {
	private static final long serialVersionUID = 1L;
	
	/**
	 * id of file. Automatically generated by database.
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;
	
	/**
	 * {@link com.info.model.Company} this file belongs to.
	 */
	@ManyToOne
    @JoinColumn(name="comp_id", nullable=false)
	private Company company;
	
	/**
	 * Name of file.
	 */
	@Column(name="file_name")
	private String name;
	
	/**
	 * Content of a file represented as array of bytes.
	 */
	@Lob
	@Column(columnDefinition="BLOB NOT NULL")
	private byte[] file;

	/**
	 * Default constructor.
	 */
	public File() {
		super();
	}

	/**
	 * Getter method for {@link #id}.
	 * @return id of file.
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * Setter method for {@link #id}.
	 * @param id id of file to set.
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * Getter method for {@link #company}.
	 * @return company of this file.
	 */
	public Company getCompany() {
		return company;
	}

	/**
	 * Setter method for {@link #company}.
	 * @param company company of this file to set.
	 */
	public void setCompany(Company company) {
		this.company = company;
	}

	/**
	 * Getter method for {@link #name}.
	 * @return name of file.
	 */
	public String getName() {
		return name;
	}

	/**
	 * Setter method for {@link #name}.
	 * @param name name of file to set.
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Getter method for {@link #file}.
	 * @return content of file as array of bytes.
	 */
	public byte[] getFile() {
		return file;
	}

	/**
	 * Setter method for {@link #file}.
	 * @param file content of file to set.
	 */
	public void setFile(byte[] file) {
		this.file = file;
	}
}
